os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - "~/.m2/repository"
before_install:
- bash .util/build_xatkit.sh
script:
- mvn install
notifications:
  slack:
    secure: ODtQU3ToYpWM+VnVxWsnLuMLg5r/FYc5Y1iImRZR0growPArCedBPinKu0CmQp4cg1TC+6e6P6UWj0j09aH0HO/cuhSO7w6Vjnp7kGRW+4kK30TSTYhUmaTeH6GP2YSWMqBqb3C5Kd40Q1scdW/vs6qWK+LpjtpIEhoixAi37CUYhKJUsj7zSKLOBztr0A/SJM8xgI1spsGMh885OlyMagHNOdXpNrHBojJKJCcNwO9wma4b+/78aTpoZtqv+JGkIf9yg3vXVEaKqXwsK9P1Ksuyrl92WVA/KgoYiScdC7lXz2ziwK6PVQeX32Ak3JFzQpNTAGPnNcVjyxpou3NvtKEzBznTYIdtn6dYLq2z1iVWI8e0R/4J2+uyM9ZYQCa7BK6Nj4hXjjOeRasumZJy4UC4A1ZzWh+UmjezhuNGUq/zwTQQDepPJQZgqKkLACx7jiRWioiCqrR6C2AD3mY+WSUAM7VecR/w8NXkABRxMWJjctB8kv9dc5zNgztIvqzKU/RGZzkj6AsFuqr54h096vFKF5v3wBUM/vjAQtZkLcNWEWnh8S5nazm9uLjxwiAQPt3RJiA18s3XNeJE4WJdkjoktSaHEuLed3sEJZVrdws74dLX/WTdQqwoXE3XyedrrNqxnK99nGLVaZ8Rs9xHwKL09rfzeWEzXYNhvWpTzWY=
